name: Update Dependencies

on:
    schedule:
        -   cron: '0 0 * * 1'  # Tous les lundis à minuit
    workflow_dispatch:      # Permet de lancer manuellement

jobs:
    update-deps:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0  # Important pour release-it

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '20'
                    cache: 'npm'

            -   name: Install dependencies
                run: npm install

            -   name: Update dependencies
                run: |
                    # Mise à jour des dépendances de développement
                    npx npm-check-updates '/^@.*/' -u
                    npx npm-check-updates -u
                    npm install

            -   name: Run tests
                run: npm run test

            -   name: Run lint
                run: npm run lint

            -   name: Build
                run: npm run build

            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v6
                with:
                    commit-message: "chore: update dependencies"
                    title: "📦 Update dependencies"
                    body: |
                        # Mise à jour automatique des dépendances
                        
                        ✅ Tests passés
                        ✅ Build réussi
                        ✅ Lint validé
                        
                        ## Changements
                        Les dépendances suivantes ont été mises à jour vers leurs dernières versions :
                        - Toutes les dépendances de développement (@types/*, eslint, etc.)
                        
                        Veuillez vérifier les changements avant de merger.
                    branch: "chore/update-dependencies"
                    labels: |
                        dependencies
                        automated pr
                    delete-branch: true

            -   name: Check PR Status
                if: success()
                run: |
                    echo "✅ Pull Request créée avec succès"
                    echo "Vous pouvez maintenant examiner les changements et merger si tout est en ordre"