name: Auto Update & Release

on:
    schedule:
        -   cron: '0 0 * * 1'
    workflow_dispatch:

jobs:
    update-and-release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: '20'
                    registry-url: 'https://registry.npmjs.org'

            -   name: Configure Git
                run: |
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"
                    git config --global user.name "GitHub Actions Bot"

            -   name: Install dependencies
                run: npm install

            -   name: Update ALL dependencies
                run: |
                    npx npm-check-updates -u
                    npm install

            -   name: Test and build
                run: |
                    npm run test
                    npm run build

            -   name: Release
                run: npm run release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}